version: '3'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_flask_Nginx_uWSGI
    volumes:
      - ./:/workspace
    stdin_open: true
    tty: true
    ports:
    - "80:80"